-- ============================================================================
-- EMERGENCY FIX - Google OAuth 403 Error
-- ============================================================================
-- Note: This migration skipped as 'profiles' table doesn't exist in current database
-- If you need OAuth fixes, apply manually when table is present.
-- ============================================================================;
